version: '3'

services:
  postgres:
    image: postgres:13.3
    container_name: "postgres_test"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
